FROM docker.io/library/node:lts-alpine AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

FROM docker.io/library/node:lts-alpine AS builder
WORKDIR /app
ARG NEXT_PUBLIC_BASE_PATH
ARG NEXT_PUBLIC_APP_ENV=production
ENV NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}
ENV NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM docker.io/library/node:lts-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
USER node
CMD ["node", "server.js"]
